### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by tammar96** [cylgom/ly#43] opened 2018-07-28 13:51 UTC
Is there any way to support HiDPI displays?

**Comment by tammar96** [comment] 2018-07-28 14:01
When using consolefont for HiDPI `latarcyrheb-sun32` I can only see the left top quarter of the UI.

**Comment by oxodao** [comment] 2018-07-29 16:15
On my desktop computer it also do not center at all

**Comment by cylgom** [comment] 2018-08-09 19:54
This is likely caused by the tty not detecting the correct screen size, I unfortunately have no idea on how to fix that :(

**Comment by tammar96** [comment] 2018-08-15 10:38
Is there any way to manually change the screen size? Like somewhere in the code where you get the screen size from tty?

**Comment by cylgom** [comment] 2018-09-23 14:36
fixed in upcoming version

**Closed by cylgom** 2018-09-23 14:36 UTC

**Comment by Mati24** [comment] 2019-07-10 16:32
Hello,
How can we change the screen size ? I have a 13" with 3840x2180. In wayland, I set the scale by 2

**Comment by oxodao** [comment] 2019-07-12 07:32
I'm worried that there is nothing much to do. According to the [Arch wiki](https://wiki.archlinux.org/index.php/HiDPI#Linux_console) the console can only change it's font size to make thing bigger...

**Comment by Mati24** [comment] 2019-07-12 07:43
Too bad, thank you :)
